### Numpy

In [2]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.2/21.2 MB 1.6 MB/s eta 0:00:0000:0100:01


In [3]:
import numpy as np

#### 1-D array

In [5]:
arr1=np.array([1,2,3,4])
print(arr1)
print(arr1.shape)
print(type(arr1))

[1 2 3 4]
(4,)
<class 'numpy.ndarray'>


In [9]:
#converting 1d to 2d

newarr=arr1.reshape((1,4))
print(newarr)
newarr.shape

[[1 2 3 4]]


(1, 4)

In [11]:
newarr1=arr1.reshape((4,1))
print(newarr1)
newarr1.shape

[[1]
 [2]
 [3]
 [4]]


(4, 1)

In [13]:
#create 2d array manually 

arr2=np.array([[1,2,3],[2,3,4],[2,3,1]])
print(arr2)
arr2.shape

[[1 2 3]
 [2 3 4]
 [2 3 1]]


(3, 3)

#### inbuilt functions

In [15]:
np.arange(1,10,1)   #create array on the basis of the start, end point and steps

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.ones((2,2)) #create the array of all 1s

array([[1., 1.],
       [1., 1.]])

In [18]:
np.zeros((2,2)) # create array of zeros 

array([[0., 0.],
       [0., 0.]])

In [20]:
#identity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
arr1=np.array([[1,23,3],[43,54,6],[22,3,5]])

print(arr1.shape) #shape
print(arr1.ndim) #dimension
print(arr1.size) #number of element
print(arr1.itemsize) #size
print(arr1.dtype) # type

(3, 3)
2
9
8
int64


In [29]:
#vectorized operations
#element wise operation
arr1=np.array([1,2,3])
arr2=np.array([2,11,2])


print("Addition:",arr1+arr2)
print("Subtraction:",arr1-arr2)
print("Multiplication:",arr1*arr2)
print("Divide:",arr1/arr2)

Addition: [ 3 13  5]
Subtraction: [-1 -9  1]
Multiplication: [ 2 22  6]
Divide: [0.5        0.18181818 1.5       ]


In [30]:
#universal operation which performed on whole array

print(np.sqrt(arr1))
print(np.log(arr1))
print(np.exp(arr1))
print(np.sin(arr1))

[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]


#### Indexing and slicing 

In [31]:
arr=np.array([[1,1,2],[12,34,55],[12,24,12]])
print("Array:\n", arr)

Array:
 [[ 1  1  2]
 [12 34 55]
 [12 24 12]]


In [32]:
#indexing

arr[0] #-> row index

array([1, 1, 2])

In [34]:
arr[0][1] #-> [row][column] 1st row second value 

np.int64(1)

In [42]:
#slicing

arr[0:2,0:2]

array([[ 1,  1],
       [12, 34]])

In [45]:
#last four element 

arr[1:3,1:3]

array([[34, 55],
       [24, 12]])

In [47]:
#statistical operations

print("mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Standard deviation:",np.std(arr))
print("Variance:",np.var(arr))

mean: 17.0
Median: 12.0
Standard deviation: 16.97710877099579
Variance: 288.22222222222223
